version: 2
updates:
  - package-ecosystem: nuget
    directory: "Projects/project.ad/packages.config/"
    schedule:
        interval: "daily"
        # day: "wednesday"
        time: "19:07"
    open-pull-requests-limit: 2

