# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "Projects/project.ad/packages.config/" # Location of package manifests
    schedule:
      interval: "weekly"
        # day: "wednesday"
    target-branch: "main"
    reviewers:
      - "MRRSoft/znode-base-maintainers"

  - package-ecosystem: nuget
    directory: "."    
    schedule:
      interval: "daily"
      time: "12:52"
    target-branch: "main"
      
      
# version: 2
# updates:
#   - package-ecosystem: nuget
#     directory: "Projects/project.ad/packages.config/"
#     schedule:
#         interval: "daily"
#         # day: "wednesday"
#         time: "19:25"
